### ISSUE TITLE
After OctoPrint update to 1.5.1 no Connection to Hue Bridge

### ISSUE THREAD

**Issue by Daddycool2708** [LMS0815/OctoPrint-hueCommands#3] opened 2020-12-14 21:35 UTC
It Worked flawless with 1.4 but after the Update to 1.5.1 I can not send any codes and I don't receive any Light information.

**Comment by Daddycool2708** [comment] 2020-12-14 21:43
OK I can send codes now but I can not set any Presets

**Comment by LMS0815** [comment] 2020-12-15 11:13
THX for reporting, I am working on a solution. Might take a while.

**Comment by Daddycool2708** [comment] 2020-12-15 11:41
Now I went back to Octoprint 1.4.2 but I can not set the RGB color anymore. I only can set the Color Temperature. But THX for working on it. It an outstanding Plug-in for Octoprint users with a Hue Bridge. Thanks for you effort and work.

**Comment by jneilliii** [comment] 2020-12-15 17:42
I'd probably lean toward the issue being related to dependentObservable in your code. That's something I've never used before so not 100% sure that's the cause, but what has probably hit you is the knockout version update that's in OctoPrint 1.5.0+. It went from 3.4.0 to 3.5.1. https://github.com/knockout/knockout/releases

**Comment by LMS0815** [comment] 2020-12-16 17:21
Should be fixed.

Please try: `https://github.com/LMS0815/OctoPrint-hueCommands/archive/develop.zip`

**Comment by Daddycool2708** [comment] 2020-12-16 18:35
Ok it work now, but I can not set RGB Colors anymore. I knew it worked after the first install. But thanks for you effort.

**Comment by Daddycool2708** [comment] 2020-12-16 18:56
But I think the RGB is a Problem on my side. I just found out that I can't control the RGB mode of the Light strip with the API Debug Tool. But i can control it with the Hue App on my Phone.

**Comment by LMS0815** [comment] 2020-12-17 08:43
Thank you for confirming. As RGB is OK in test environment I merged this into master.
Please report a new bug (with the button) if required.

**Closed as completed by LMS0815** 2020-12-17 08:43 UTC
Labels: bug
